--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-08-04 09:22:28

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16390)
-- Name: question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question (
    id integer NOT NULL,
    question_title character varying(255) NOT NULL,
    option1 character varying(255) NOT NULL,
    option2 character varying(255) NOT NULL,
    option3 character varying(255) NOT NULL,
    option4 character varying(255) NOT NULL,
    right_answer character varying(255) NOT NULL,
    difficulty_level text NOT NULL,
    category character varying(255) NOT NULL,
    dificultylevel character varying(255)
);


ALTER TABLE public.question OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.question_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.question_id_seq OWNER TO postgres;

--
-- TOC entry 4814 (class 0 OID 0)
-- Dependencies: 217
-- Name: question_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.question_id_seq OWNED BY public.question.id;


--
-- TOC entry 219 (class 1259 OID 16434)
-- Name: question_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.question_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.question_seq OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24577)
-- Name: quiz; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz (
    id integer NOT NULL,
    title character varying(255)
);


ALTER TABLE public.quiz OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 24576)
-- Name: quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24582)
-- Name: quiz_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_questions (
    quiz_id integer NOT NULL,
    questions_id integer NOT NULL
);


ALTER TABLE public.quiz_questions OWNER TO postgres;

--
-- TOC entry 4651 (class 2604 OID 16393)
-- Name: question id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question ALTER COLUMN id SET DEFAULT nextval('public.question_id_seq'::regclass);


--
-- TOC entry 4804 (class 0 OID 16390)
-- Dependencies: 218
-- Data for Name: question; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.question (id, question_title, option1, option2, option3, option4, right_answer, difficulty_level, category, dificultylevel) FROM stdin;
1	Which Java keyword is used to create a subclass?	class	interface	extends	implements	extends	Easy	Java	\N
2	What is the output of the following Java code snippet? \\nint x = 5; \\nSystem.out.println(x++);	4	5	6	Compile error	5	Easy	Java	\N
3	In Java, what is the default value of an uninitialized boolean variable?	TRUE	FALSE	0	null	FALSE	Easy	Java	\N
4	Which Java keyword is used to explicitly throw an exception?	try	throw	catch	finally	throw	Easy	Java	\N
5	What does the 'static' keyword mean in Java?	It indicates that a variable is constant.	It indicates that a method can be accessed without creating an instance of the class.	It indicates that a class cannot be extended.	It indicates that a variable is of primitive type.	It indicates that a method can be accessed without creating an instance of the class.	Easy	Java	\N
6	What is the correct way to declare a constant variable in Java?	constant int x = 5;	final int x = 5;	static int x = 5;	readonly int x = 5;	final int x = 5;	Easy	Java	\N
7	Which loop in Java allows the code to be executed at least once?	for loop	while loop	do-while loop	switch loop	do-while loop	Easy	Java	\N
8	What is the purpose of the 'break' statement in Java?	To terminate a loop or switch statement and transfer control to the next statement.	To skip the rest of the code in a loop and move to the next iteration.	To define a label for a loop or switch statement.	To check a condition and execute a block of code repeatedly.	To terminate a loop or switch statement and transfer control to the next statement.	Easy	Java	\N
9	Which Java operator is used to concatenate two strings?	+	-	*	/	+	Easy	Java	\N
10	In Java, which collection class provides an implementation of a dynamic array?	HashMap	ArrayList	LinkedList	HashSet	ArrayList	Easy	Java	\N
11	Which Python function is used to calculate the length of a list?	count()	size()	length()	len()	len()	Easy	Python	\N
12	What is the output of the following Python code snippet? \\nx = [1, 2, 3] \\nx.append(4) \\nprint(x)	[1, 2, 3]	[1, 2, 3, 4]	[4, 3, 2, 1]	Error	[1, 2, 3, 4]	Easy	Python	\N
13	Which Python statement is used to exit from a loop prematurely?	break	continue	pass	return	break	Easy	Python	\N
14	What is the purpose of the 'range()' function in Python?	To generate a random number within a given range.	To iterate over a sequence of numbers.	To sort a list in ascending order.	To calculate the length of a string.	To iterate over a sequence of numbers.	Easy	Python	\N
15	In Python, which data type is mutable?	int	float	str	list	list	Easy	Python	\N
16	Which Python module is used for working with dates and times?	datetime	math	os	sys	datetime	Easy	Python	\N
\.


--
-- TOC entry 4807 (class 0 OID 24577)
-- Dependencies: 221
-- Data for Name: quiz; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz (id, title) FROM stdin;
\.


--
-- TOC entry 4808 (class 0 OID 24582)
-- Dependencies: 222
-- Data for Name: quiz_questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_questions (quiz_id, questions_id) FROM stdin;
\.


--
-- TOC entry 4815 (class 0 OID 0)
-- Dependencies: 217
-- Name: question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.question_id_seq', 16, true);


--
-- TOC entry 4816 (class 0 OID 0)
-- Dependencies: 219
-- Name: question_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.question_seq', 1, false);


--
-- TOC entry 4817 (class 0 OID 0)
-- Dependencies: 220
-- Name: quiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_id_seq', 1, false);


--
-- TOC entry 4653 (class 2606 OID 16397)
-- Name: question question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (id);


--
-- TOC entry 4655 (class 2606 OID 24581)
-- Name: quiz quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz
    ADD CONSTRAINT quiz_pkey PRIMARY KEY (id);


--
-- TOC entry 4656 (class 2606 OID 24590)
-- Name: quiz_questions fkcgp9e1c6ww3t383aui4w8feae; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT fkcgp9e1c6ww3t383aui4w8feae FOREIGN KEY (quiz_id) REFERENCES public.quiz(id);


--
-- TOC entry 4657 (class 2606 OID 24585)
-- Name: quiz_questions fkpmfvwer12y1nrjc0efm04dq16; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT fkpmfvwer12y1nrjc0efm04dq16 FOREIGN KEY (questions_id) REFERENCES public.question(id);


-- Completed on 2025-08-04 09:22:28

--
-- PostgreSQL database dump complete
--

